palette = 0=#000000
palette = 1=#FFE1A8
palette = 2=#83A0A0
palette = 3=#545454
palette = 4=#707070
palette = 5=#8c8c8c
palette = 6=#21FA90
palette = 7=#eeeeee
palette = 8=#e0e0e0
palette = 9=#ffffff
palette = 10=#ff4500
palette = 11=#32cd32
palette = 12=#1e90ff
palette = 13=#ffd700
palette = 14=#ff69b4
palette = 15=#00ced1
background =#2B3D41
foreground = #ffffff
cursor-color = #ffffff
selection-background = #4C5F6B
selection-foreground = #ffffff